let imageUrl = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/"
// Pokemons array
const pokemon = [
  { id: 1, name: 'Bulbasaur', type: 'Planta / Veneno', image: imageUrl + "1.png" },
  { id: 2, name: 'Ivysaur', type: 'Planta / Veneno', image: imageUrl + "2.png" },
  { id: 3, name: 'Venusaur', type: 'Planta / Veneno', image: imageUrl + "3.png" },
  { id: 4, name: 'Charmander', type: 'Fuego', image: imageUrl + "4.png" },
  { id: 5, name: 'Charmeleon', type: 'Fuego', image: imageUrl + "5.png" },
  { id: 6, name: 'Charizard', type: 'Fuego / Volador', image: imageUrl + "6.png" },
  { id: 7, name: 'Squirtle', type: 'Agua', image: imageUrl + "7.png" },
  { id: 8, name: 'Wartortle', type: 'Agua', image: imageUrl + "8.png" },
  { id: 9, name: 'Blastoise', type: 'Agua', image: imageUrl + "9.png" },
  { id: 10, name: 'Caterpie', type: 'Bicho', image: imageUrl + "10.png" },
  { id: 11, name: 'Metapod', type: 'Bicho', image: imageUrl + "11.png" },
  { id: 12, name: 'Butterfree', type: 'Bicho / Volador', image: imageUrl + "12.png" },
  { id: 13, name: 'Weedle', type: 'Bicho / Veneno', image: imageUrl + "13.png" },
  { id: 14, name: 'Kakuna', type: 'Bicho / Veneno', image: imageUrl + "14.png" },
  { id: 15, name: 'Beedrill', type: 'Bicho / Veneno', image: imageUrl + "15.png" },
  { id: 16, name: 'Pidgey', type: 'Normal / Volador', image: imageUrl + "16.png" },
  { id: 17, name: 'Pidgeotto', type: 'Normal / Volador', image: imageUrl + "17.png" },
  { id: 18, name: 'Pidgeot', type: 'Normal / Volador', image: imageUrl + "18.png" },
  { id: 19, name: 'Rattata', type: 'Normal', image: imageUrl + "19.png" },
  { id: 20, name: 'Raticate', type: 'Normal', image: imageUrl + "20.png" },
  { id: 21, name: 'Spearow', type: 'Normal / Volador', image: imageUrl + "21.png" },
  { id: 22, name: 'Fearow', type: 'Normal / Volador', image: imageUrl + "22.png" },
  { id: 23, name: 'Ekans', type: 'Veneno', image: imageUrl + "23.png" },
  { id: 24, name: 'Arbok', type: 'Veneno', image: imageUrl + "24.png" },
  { id: 25, name: 'Pikachu', type: 'Eléctrico', image: imageUrl + "25.png" },
  { id: 26, name: 'Raichu', type: 'Eléctrico', image: imageUrl + "26.png" },
  { id: 27, name: 'Sandshrew', type: 'Tierra', image: imageUrl + "27.png" },
  { id: 28, name: 'Sandslash', type: 'Tierra', image: imageUrl + "28.png" },
  { id: 29, name: 'Nidoran♀', type: 'Veneno', image: imageUrl + "29.png" },
  { id: 30, name: 'Nidorina', type: 'Veneno', image: imageUrl + "30.png" },
  { id: 31, name: 'Nidoqueen', type: 'Veneno / Tierra', image: imageUrl + "31.png" },
  { id: 32, name: 'Nidoran♂', type: 'Veneno', image: imageUrl + "32.png" },
  { id: 33, name: 'Nidorino', type: 'Veneno', image: imageUrl + "33.png" },
  { id: 34, name: 'Nidoking', type: 'Veneno / Tierra', image: imageUrl + "34.png" },
  { id: 35, name: 'Clefairy', type: 'Hada', image: imageUrl + "35.png" },
  { id: 36, name: 'Clefable', type: 'Hada', image: imageUrl + "36.png" },
  { id: 37, name: 'Vulpix', type: 'Fuego', image: imageUrl + "37.png" },
  { id: 38, name: 'Ninetales', type: 'Fuego', image: imageUrl + "38.png" },
  { id: 39, name: 'Jigglypuff', type: 'Normal / Hada', image: imageUrl + "39.png" },
  { id: 40, name: 'Wigglytuff', type: 'Normal / Hada', image: imageUrl + "40.png" },
  { id: 41, name: "Zubat", type: "Veneno/Volador", image: imageUrl + "41.png"},
  { id: 42, name: "Golbat", type: "Veneno/Volador", image: imageUrl + "42.png"},
  { id: 43, name: "Oddish", type: "Planta/Veneno", image: imageUrl + "43.png"},
  { id: 44, name: "Gloom", type: "Planta/Veneno", image: imageUrl + "44.png"},
  { id: 45, name: "Vileplume", type: "Planta/Veneno", image: imageUrl + "45.png"},
  { id: 46, name: "Paras", type: "Bicho/Planta", image: imageUrl + "46.png"},
  { id: 47, name: "Parasect", type: "Bicho/Planta", image: imageUrl + "47.png"},
  { id: 48, name: "Venonat", type: "Bicho/Veneno", image: imageUrl + "48.png"},
  { id: 49, name: "Venomoth", type: "Bicho/Veneno", image: imageUrl + "49.png"},
  { id: 50, name: "Diglett", type: "Tierra", image: imageUrl + "50.png"},
  { id: 51, name: "Dugtrio", type: "Tierra", image: imageUrl + "51.png"},
  { id: 52, name: "Meowth", type: "Normal", image: imageUrl + "52.png"},
  { id: 53, name: "Persian", type: "Normal", image: imageUrl + "53.png"},
  { id: 54, name: "Psyduck", type: "Agua", image: imageUrl + "54.png"},
  { id: 55, name: "Golduck", type: "Agua", image: imageUrl + "55.png"},
  { id: 56, name: "Mankey", type: "Lucha", image: imageUrl + "56.png"},
  { id: 57, name: "Primeape", type: "Lucha", image: imageUrl + "57.png"},
  { id: 58, name: "Growlithe", type: "Fuego", image: imageUrl + "58.png"},
  { id: 59, name: "Arcanine", type: "Fuego", image: imageUrl + "59.png"},
  { id: 60, name: "Poliwag", type: "Agua", image: imageUrl + "60.png"},
  { id: 61, name: "Poliwhirl", type: "Agua", image: imageUrl + "61.png"},
  { id: 62, name: "Poliwrath", type: "Agua/Lucha", image: imageUrl + "62.png"},
  { id: 63, name: "Abra", type: "Psíquico", image: imageUrl + "63.png"},
  { id: 64, name: "Kadabra", type: "Psíquico", image: imageUrl + "64.png"},
  { id: 65, name: "Alakazam", type: "Psíquico", image: imageUrl + "65.png"},
  { id: 66, name: "Machop", type: "Lucha", image: imageUrl + "66.png"},
  { id: 67, name: "Machoke", type: "Lucha", image: imageUrl + "67.png"},
  { id: 68, name: "Machamp", type: "Lucha", image: imageUrl + "68.png"},
  { id: 69, name: "Bellsprout", type: "Planta/Veneno", image: imageUrl + "69.png"},
  { id: 70, name: "Weepinbell", type: "Planta/Veneno", image: imageUrl + "70.png"},
  { id: 71, name: "Victreebel", type: "Planta/Veneno", image: imageUrl + "71.png"},
  { id: 72, name: "Tentacool", type: "Agua/Veneno", image: imageUrl + "72.png"},
  { id: 73, name: "Tentacruel", type: "Agua/Veneno", image: imageUrl + "73.png"},
  { id: 74, name: "Geodude", type: "Roca/Tierra", image: imageUrl + "74.png"},
  { id: 75, name: "Graveler", type: "Roca/Tierra", image: imageUrl + "75.png"},
  { id: 76, name: "Golem", type: "Roca/Tierra", image: imageUrl + "76.png"},
  { id: 77, name: "Ponyta", type: "Fuego", image: imageUrl + "77.png"},
  { id: 78, name: "Rapidash", type: "Fuego", image: imageUrl + "78.png"},
  { id: 79, name: "Slowpoke", type: "Agua/Psíquico", image: imageUrl + "79.png"},
  { id: 80, name: "Slowbro", type: "Agua/Psíquico", image: imageUrl + "80.png"},
  { id: 81, name: "Magnemite", type: "Eléctrico/Acero", image: imageUrl + "81.png"},
  { id: 82, name: "Magneton", type: "Eléctrico/Acero", image: imageUrl + "82.png"},
  { id: 83, name: "Farfetch'd", type: "Normal/Volador", image: imageUrl + "83.png"},
  { id: 84, name: "Doduo", type: "Normal/Volador", image: imageUrl + "84.png"},
  { id: 85, name: "Dodrio", type: "Normal/Volador", image: imageUrl + "85.png"},
  { id: 86, name: "Seel", type: "Agua", image: imageUrl + "86.png"},
  { id: 87, name: "Dewgong", type: "Agua/Hielo", image: imageUrl + "87.png"},
  { id: 88, name: "Grimer", type: "Veneno", image: imageUrl + "88.png"},
  { id: 89, name: "Muk", type: "Veneno", image: imageUrl + "89.png"},
  { id: 90, name: "Shellder", type: "Agua", image: imageUrl + "90.png"},
  { id: 91, name: "Cloyster", type: "Agua/Hielo", image: imageUrl + "91.png"},
  { id: 92, name: "Gastly", type: "Fantasma/Veneno", image: imageUrl + "92.png"},
  { id: 93, name: "Haunter", type: "Fantasma/Veneno", image: imageUrl + "93.png"},
  { id: 94, name: "Gengar", type: "Fantasma/Veneno", image: imageUrl + "94.png"},
  { id: 95, name: "Onix", type: "Roca/Tierra", image: imageUrl + "95.png"},
  { id: 96, name: "Drowzee", type: "Psíquico", image: imageUrl + "96.png"},
  { id: 97, name: "Hypno", type: "Psíquico", image: imageUrl + "97.png"},
  { id: 98, name: "Krabby", type: "Agua", image: imageUrl + "98.png"},
  { id: 99, name: "Kingler", type: "Agua", image: imageUrl + "99.png"},
  { id: 100, name: "Voltorb", type: "Eléctrico", image: imageUrl + "100.png"},
  { id: 101, name: "Electrode", type: "Eléctrico", image: imageUrl + "101.png"},
  { id: 102, name: "Exeggcute", type: "Planta/Psíquico", image: imageUrl + "102.png"},
  { id: 103, name: "Exeggutor", type: "Planta/Psíquico", image: imageUrl + "103.png"},
  { id: 104, name: "Cubone", type: "Tierra", image: imageUrl + "104.png"},
  { id: 105, name: "Marowak", type: "Tierra", image: imageUrl + "105.png"},
  { id: 106, name: "Hitmonlee", type: "Lucha", image: imageUrl + "106.png"},
  { id: 107, name: "Hitmonchan", type: "Lucha", image: imageUrl + "107.png"},
  { id: 108, name: "Lickitung", type: "Normal", image: imageUrl + "108.png"},
  { id: 109, name: "Koffing", type: "Veneno", image: imageUrl + "109.png"},
  { id: 110, name: "Weezing", type: "Veneno", image: imageUrl + "110.png"},
  { id: 111, name: "Rhyhorn", type: "Tierra/Roca", image: imageUrl + "111.png"},
  { id: 112, name: "Rhydon", type: "Tierra/Roca", image: imageUrl + "112.png"},
  { id: 113, name: "Chansey", type: "Normal", image: imageUrl + "113.png"},
  { id: 114, name: "Tangela", type: "Planta", image: imageUrl + "114.png"},
  { id: 115, name: "Kangaskhan", type: "Normal", image: imageUrl + "115.png"},
  { id: 116, name: "Horsea", type: "Agua", image: imageUrl + "116.png"},
  { id: 117, name: "Seadra", type: "Agua", image: imageUrl + "117.png"},
  { id: 118, name: "Goldeen", type: "Agua", image: imageUrl + "118.png"},
  { id: 119, name: "Seaking", type: "Agua", image: imageUrl + "119.png"},
  { id: 120, name: "Staryu", type: "Agua", image: imageUrl + "120.png"},
  { id: 121, name: "Starmie", type: "Agua/Psíquico", image: imageUrl + "121.png"},
  { id: 122, name: "Mr. Mime", type: "Psíquico/Hada", image: imageUrl + "122.png"},
  { id: 123, name: "Scyther", type: "Bicho/Volador", image: imageUrl + "123.png"},
  { id: 124, name: "Jynx", type: "Hielo/Psíquico", image: imageUrl + "124.png"},
  { id: 125, name: "Electabuzz", type: "Eléctrico", image: imageUrl + "125.png"},
  { id: 126, name: "Magmar", type: "Fuego", image: imageUrl + "126.png"},
  { id: 127, name: "Pinsir", type: "Bicho", image: imageUrl + "127.png"},
  { id: 128, name: "Tauros", type: "Normal", image: imageUrl + "128.png"},
  { id: 129, name: "Magikarp", type: "Agua", image: imageUrl + "129.png"},
  { id: 130, name: "Gyarados", type: "Agua/Volador", image: imageUrl + "130.png"},
  { id: 131, name: "Lapras", type: "Agua/Hielo", image: imageUrl + "131.png"},
  { id: 132, name: "Ditto", type: "Normal", image: imageUrl + "132.png"},
  { id: 133, name: "Eevee", type: "Normal", image: imageUrl + "133.png"},
  { id: 134, name: "Vaporeon", type: "Agua", image: imageUrl + "134.png"},
  { id: 135, name: "Jolteon", type: "Eléctrico", image: imageUrl + "135.png"},
  { id: 136, name: "Flareon", type: "Fuego", image: imageUrl + "136.png"},
  { id: 137, name: "Porygon", type: "Normal", image: imageUrl + "137.png"},
  { id: 138, name: "Omanyte", type: "Roca/Agua", image: imageUrl + "138.png"},
  { id: 139, name: "Omastar", type: "Roca/Agua", image: imageUrl + "139.png"},
  { id: 140, name: "Kabuto", type: "Roca/Agua", image: imageUrl + "140.png"},
  { id: 141, name: "Kabutops", type: "Roca/Agua", image: imageUrl + "141.png"},
  { id: 142, name: "Aerodactyl", type: "Roca/Volador", image: imageUrl + "142.png"},
  { id: 143, name: "Snorlax", type: "Normal", image: imageUrl + "143.png"},
  { id: 144, name: "Articuno", type: "Hielo/Volador", image: imageUrl + "144.png"},
  { id: 145, name: "Zapdos", type: "Eléctrico/Volador", image: imageUrl + "145.png"},
  { id: 146, name: "Moltres", type: "Fuego/Volador", image: imageUrl + "146.png"},
  { id: 147, name: "Dratini", type: "Dragón", image: imageUrl + "147.png"},
  { id: 148, name: "Dragonair", type: "Dragón", image: imageUrl + "148.png"},
  { id: 149, name: "Dragonite", type: "Dragón/Volador", image: imageUrl + "149.png"},
  { id: 150, name: "Mewtwo", type: "Psíquico", image: imageUrl + "150.png"},
  { id: 151, name: "Mew", type: "Psíquico", image: imageUrl + "151.png"}
];

module.exports = { pokemon };